### ISSUE TITLE
SharpPcap is not working with latest npcap

### ISSUE THREAD

**Issue by nono3551** [chmorgan/sharppcap#69] opened 2019-06-03 18:36 UTC
After I try to open device I get an error.

_device?.Open(DeviceMode.Promiscuous, 1000);

PcapException: Unable to activate the adapter (rpcap://\Device\NPF_{34BF6DC1-DD25-4C19-8E90-0DFB48B1529C}). Return code: -1

I am using npcap 0.995 and SharpPcap v4.6.1

**Comment by bmenees** [comment] 2019-06-12 12:47
I've run into this too. To work around it I went to https://nmap.org/npcap/dist/ and downgraded to older Npcap versions until I found one that worked. I tried 0.995 through 0.992 without success, but then [0.991](https://nmap.org/npcap/dist/npcap-0.991.exe) worked. I installed it using the default options.

![image](https://user-images.githubusercontent.com/13545825/59352045-5c924500-8ce5-11e9-88ca-6a9f7350cd0f.png)

I don't know if this is a bug in SharpPcap or Npcap. It's going to continue to be a problem though since Wireshark is currently installing 0.995, which doesn't work with SharpPcap. :-(

FWIW, I'm on Windows 10 v1903.

**Comment by TheEyesOfTheLastWitness** [comment] 2019-06-26 07:57
Until 2 days ago, I was using Sharppcap v4.2.0, which worked with the last Npcap (v0.996) perfectly. Once I upgraded Sharppcap to v4.6.1, however, I started getting the same error and since then I have been unable to do anything about it. Note that I am using 

_device.Open(DeviceMode.Normal);

**Comment by larswilliam** [comment] 2019-06-26 20:51
After reading bmenees comment above I got inspired and rolled back the Npcap to 0.991 and got surprised!

SharpPcap 4.6.1 in combination with Npcap 0.991 works as supposed with monitor mode :-)

Thanks @bmenees !

**Comment by chmorgan** [comment] 2019-06-26 20:53
Could I trouble someone with the issue to report it to the npcap project on GitHub? It may be something we are doing wrong or that they've changed.

**Comment by larswilliam** [comment] 2019-06-26 21:06
Sure Chris, but I will need to do some effort - in order to better understand what really is the issue here.

**Comment by bmenees** [comment] 2019-06-27 13:51
Here's a really bizarre update that may help. I'm using SharpPcap 4.6.1 with Npcap 0.995 now without problems.  The only thing I did was change some code in my project from using WinPcapDevice* to LipPcapLiveDevice* and to stop using the WinPcapDevice.Open method.

I changed this code:
``` C#
WinPcapDeviceList devices = WinPcapDeviceList.Instance;
```
To this:
``` C#
LibPcapLiveDeviceList devices = LibPcapLiveDeviceList.Instance;
```

Then I get a device from the devices list.
``` C#
ICaptureDevice captureDevice = devices.First();
```

Then I changed this code to stop using WinPcapDevice.Open directly.
``` C#
WinPcapDevice winPcapDevice = captureDevice as WinPcapDevice;
if (winPcapDevice != null)
{
	winPcapDevice.Open(OpenFlags.Promiscuous | OpenFlags.MaxResponsiveness, readTimeoutMilliseconds);
}
else
{
	captureDevice.Open(DeviceMode.Promiscuous, readTimeoutMilliseconds);
}
```
Now I always do this:
``` C#
captureDevice.Open(DeviceMode.Promiscuous, readTimeoutMilliseconds);
```
I'm not sure _why_ this fixed my problem, but I'm good now. I drilled into SharpPcap's code for WinPcapDevice.Open and LibPcapLiveDevice.Open, and they are _significantly_ different. Maybe something changed in Npcap 0.992+ so the differences matter.

**Comment by gudaol** [comment] 2019-07-30 06:07
Any news on this?

**Comment by chmorgan** [comment] 2019-07-30 20:54
As far as I know there hasn’t been any info about what exactly the issue
is. Sharppcap calls the npcap library. If it works with some versions of
npcap but the same latest version of SharpPcap it sounds like it could be
related to the version of npcap.

Chris

**Comment by chmorgan** [comment] 2019-09-13 23:50
Verified that latest SharpPcap from master is working with npcap 0.9983 (just installed and tested it). So not sure what the issue is here. Closing until more info can be provided.

**Closed by chmorgan** 2019-09-13 23:50 UTC
