### ISSUE TITLE
Cannot send tcp packet larger than 1500

### ISSUE THREAD

**Issue by russianbullet** [chmorgan/sharppcap#21] opened 2017-04-20 16:41 UTC
Hello 

I'm trying to send 1600 bytes packet size , but no luck 

I'll be delighted to hear from you soon 

regards

**Comment by Abdullah2993** [comment] 2017-04-20 20:16
@russianbullet MTU?

**Comment by russianbullet** [comment] 2017-04-20 20:24
abdullah I've modified the mtu of the ethernet card in windows but no luck , anything to do in sharppcap

**Comment by cmo-hms** [comment] 2017-04-21 00:26
SharpPcap doesn't contain any limits to the packet size you can send. That of course doesn't mean that there aren't limits due to wincap or npcap.

Now that npcap is supported by the latest git master would you mind trying npcap (instead of winpcap) and the latest git master to see if it works? If it doesn't then at least we can reach out to the npcap developer to discuss, winpcap is a dead project so we have no path for support there.

**Comment by chmorgan** [comment] 2017-04-21 00:27
SharpPcap doesn't contain any limits to the packet size you can send. That of course doesn't mean that there aren't limits due to wincap or npcap.

Now that npcap is supported by the latest git master would you mind trying npcap (instead of winpcap) and the latest git master to see if it works? If it doesn't then at least we can reach out to the npcap developer to discuss, winpcap is a dead project so we have no path for support there.

**Comment by russianbullet** [comment] 2017-04-21 16:38
Dear @chmorgan I've unisntalled winpcap and installed npcap , the result is the same , I get this error when SendPacket 

**> An unhandled exception of type 'SharpPcap.PcapException' occurred in SharpPcap.dll
> 
> Additional information: Can't send packet: send error: PacketSendPacket failed**

**Comment by chmorgan** [comment] 2017-04-21 18:20
Hi Yang.

I looked but there doesn't look to be an 'issues' tab on the github npcap
project.

It looks like this person is having trouble sending a large packet. I had
them switch to using npcap so we had some option to reach out to you to see
if this is an issue with npcap, the usage of the function call or what.
SharpPcap isn't doing anything with the data but forwarding it on to the
underlying library.

Chris

**Comment by russianbullet** [comment] 2017-04-21 18:26
Thank you Chris

**Comment by hsluoyz** [comment] 2017-04-22 01:08
The issues page is at Nmap repo here: https://github.com/nmap/nmap/issues

BTW, can you provide an example to reproduce this issue? It only needs to contain the sending packet call with 1600 bytes. And I will test whether it works.

And please provide your DiagReport described in Npcap README. So I can see your adapter info.

**Comment by russianbullet** [comment] 2017-04-22 09:26
Hello @hsluoyz 
It's a pleasure to be in contact with you, Thx for @chmorgan 
Dear @hsluoyz  I've made a Demo about this issue, it's written in C#, also I've attached the Report you asked for. [DiagReport-20170422-121459.txt](https://github.com/chmorgan/sharppcap/files/948868/DiagReport-20170422-121459.txt)
Thank you in advance

```
using SharpPcap;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net.NetworkInformation;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DemoSendPacket
{
public partial class frmDemo : Form
{



private SharpPcap.CaptureDeviceList devices;
public frmDemo()
{
InitializeComponent();
}

private static byte[] GetRandomPacket(int size)
{
byte[] packet = new byte[size];
Random rand = new Random();
rand.NextBytes(packet);
return packet;
}

private void frmDemo_Load(object sender, EventArgs e)
{



NetworkInterface[] nics = NetworkInterface.GetAllNetworkInterfaces();

devices = CaptureDeviceList.Instance;

foreach (ICaptureDevice dev in devices)
{

NetworkInterface ni = nics.Where((nic) => dev.Name.EndsWith(nic.Id)).FirstOrDefault();

if (ni == null)
continue;

this.cboNics.Items.Add(ni.Name);
}
}

private void btnSend1_Click(object sender, EventArgs e)
{
byte[] packet1 = GetRandomPacket(1514);
ICaptureDevice device = CaptureDeviceList.New()[this.cboNics.SelectedIndex];

device.Open();

device.SendPacket(packet1);

device.Close();
}

private void btnSend2_Click(object sender, EventArgs e)
{
byte[] packet2 = GetRandomPacket(1600);
ICaptureDevice device = CaptureDeviceList.New()[this.cboNics.SelectedIndex];

device.Open();

device.SendPacket(packet2);

device.Close();
}
}
}


```

**Comment by hsluoyz** [comment] 2017-04-22 15:17
Where is ``this.cboNics`` defined? Please upload your whole project as a zip. It's kind of hard for a non C# expert as me to tackle only a piece of code.

**Comment by russianbullet** [comment] 2017-04-24 12:08
Hello @hsluoyz , I'm so sorry to be late , I couldn't upload the project here, so I've uploaded it to google drive , this is the link: https://drive.google.com/file/d/0B6TQYhFg8n0mdXhubm5ESDdyYkE/view

**Comment by hsluoyz** [comment] 2017-04-25 13:24
Hi, I reproduced your issue. It seems that Windows hardcoded the maximum of MTU for Ethernet adapters to be 1500. In fact I never googled out an article that said MTU can be larger than 1500. It's a de-facto standard and it seems that Windows implements this way. In fact, you can get a larger MTU for other type adapters. For example, Npcap Loopback Adapter supports a MTU of 65536.

**Comment by russianbullet** [comment] 2017-04-25 17:59
Thank you @hsluoyz , It seems that am going to fragment the ip packet , thank you for your efforts guys , regards

**Comment by Abdullah2993** [comment] 2017-04-25 18:23
@hsluoyz @russianbullet i am quite sure you can change the MTU in windows. Using netsh tool...

**Comment by Abdullah2993** [comment] 2017-04-25 18:25
You can change the MTU
https://support.zen.co.uk/kb/Knowledgebase/Changing-the-MTU-size-in-Windows-Vista-7-or-8

**Comment by russianbullet** [comment] 2017-04-26 08:22
@Abdullah2993 I've already changed it , but no luck still the same error

**Comment by chmorgan** [comment] 2017-05-06 19:43
Closing this as it is a limitation of the OS and/or npcap. @hsluoyz thanks for your help.

**Closed by chmorgan** 2017-05-06 19:43 UTC
