### ISSUE TITLE
Missing 'FriendlyName' for bridged inerfaces [Windows]

### ISSUE THREAD

**Issue by theXappy** [chmorgan/sharppcap#57] opened 2018-09-01 13:41 UTC
When a connection is bridged using Windows' built in virtual bridge SharpPcap won't populate the 'FriendlyName' property of the PcapInterface object.
This is probably not an issue with WinPcap since both Wireshark and TShark are able to get the friendly name even when the connection is bridge.

How to reproduce (Windows 10, 64x):
1. Open the '**Network Connection**' window
2. **Select a pair** of Ethernet connections (if none/one exists, a loopback connection works as well [create it with hdwwiz.exe](http://nil.uniza.sk/windows/windows-10/how-install-microsoft-loopback-adapter-windows-10))
3. **Right click** one of the connection 
4. Select '**Bridge Connections**'. Uner the Connections' names it should say "Enabled, Bridged"
5. Get **CaptureDeviceList.Instance** in the code and see the Interface property of the device has FriendlyName set to NULL

Here's a shot of me debugging the same connection - once when bridged and a second time when it isn't
![image](https://user-images.githubusercontent.com/10898152/44946465-84bf5000-ae05-11e8-8232-19570f25dbe0.png)

**Comment by Wootness** [comment] 2018-09-02 16:04
I went digging in the code to see where the name is resolved (from the GUID-looking id) and found this:
In LibPcapLiveDevice.cs:
In the constructor - all NICs are retrieved using .NET's **NetworkInterface**.GetAllNetworkInterfaces()
So while the constructor is called for every adapter, including bridged ones, the list returned from LibPcapLiveDevice does not contain those.

I used dotPeek to see check the implementation of **NetworkInterface**.GetAllNetworkInterfaces() inside System.Net.NetworkInformation.dll
It calls some other functions in a chain ending in an internal class called 'SystemNetworkInterface'
There's a call there to **GetAdaptersAddresses** from **iphlpapi.dll**
My understanding is that this dll can get all adapters in the system but it can be called with filtering flags. The code in .NET always uses 2 flags:
"IncludeWinds" and "IncludeGateways"
there are several other flags including **"IncludeAllInterfaces"**
I tried calling this function by myself with that flag and received the missing NIC, along with several other 'unusual' network adapters.

Perhaps calling the IP Helper API (iphlpapi.dll) directly from sharppcap is the solution here but this is obviously a platform specific fix and resolving the names in Mac/Linux should still use .NET's GetAllNetworkInterfaces

**Comment by chmorgan** [comment] 2019-03-07 14:23
Hi @Wootness. This does look like an issue. I'm not sure anyone is available to look at it at the moment. I can leave this open but it likely won't get fixed unless you or someone else submits a PR to address it.

**Comment by Wootness** [comment] 2019-03-07 18:41
Hey Chris,
I wrote a changeset which deals with this issue. I commited it to the fork of your repo I have in my account.
While it seems to solve the problem, I have 2 reasons why I'm not sure it should be merged:
1. As mentioned the problem (and solution) is platform specific.
The changes include P/Invoke calls to iphlpapi.dll (IP Helper API) and I have no clue if that code will break compilation/run-time for OSX/Linux
As far as I understand there isn't a way to distinguish the compiling OS in SharpPcap ATM. So to tackle that I added some OS checking code into SharpPcap,csproj which basically sets a compiler constant named "Windows" iff the code is compiled on windows.
You might want to implement this differently.
Following that I just wrapped anything specific to the IP Helper API access with "#if Windows" scopes I believe it's enough but didn' try compiling on OSX/Linux.
2. To call the function in iphlpapi.dll and than wrap it in a nice .NET object (a 'fake' NetworkInterface class) I had to 'borrow' some very ugly code including structs for the P/Invoke call and decompiled code from System.Net

All the relevant changes can be seen in this commit:
https://github.com/Wootness/sharppcap/commit/535c342da96260b03697f7c04dcb9fc733b97eee

To conclude: I found a working solution but I am not sure I made the changes in the nicest way possible and don't want to 'pollute' SharpPcap's master branch with them.

**Comment by chmorgan** [comment] 2019-03-07 18:55
@Wootness ahh. Yeah we wouldn't want to add another pinvoke dependency if we could avoid it, it would break usage on macOS and linux. Is there a way to retrieve this information from a .net api instead?

**Comment by Wootness** [comment] 2019-03-09 09:29
> @Wootness ahh. Yeah we wouldn't want to add another pinvoke dependency if we could avoid it, it would break usage on macOS and linux. Is there a way to retrieve this information from a .net api instead?

None that I'm aware of.

**Comment by lextm** [comment] 2019-08-21 02:09
@Wootness Why do you need conditional compilation against Windows? Runtime check is already in place to support the current PInvoke usage,
 https://github.com/chmorgan/sharppcap/blob/master/SharpPcap/LibPcap/LibPcapSafeNativeMethods.cs#L39

**Comment by chmorgan** [comment] 2019-09-14 00:28
@Wootness how is Wireshark getting the friendly name on windows? Note that the code is open so you could check there to confirm. Also, npcap is in active development, as is libpcap so there is always some possibility to modify the upstream code to improve the situation. Agreed the guid names are ugly to look at. I'm still not convinced we want to jump to adding some 800 lines of code to resolve until we've run down those other options that could help others and are seemingly better places to put the fix.

**Comment by kayoub5** [comment] 2019-12-28 22:13
@chmorgan Wireshark is doing 
* `ConvertInterfaceGuidToLuid` followed by `ConvertInterfaceLuidToAlias` on Windows Vista and later.
* `NhGetInterfaceNameFromGuid` undocumented function otherwise.

Both from hIPHlpApi.

A small helper class for this would be around 30-40 lines of code.

**Comment by chmorgan** [comment] 2019-12-29 01:39
@kayoub5 should we ask the .net core guys to add support for this to .net? Then we wouldn't need more non-net code and we could potentially get cross platform support, if there is some equivalent for Mac/Linux.

**Comment by kayoub5** [comment] 2019-12-29 07:44
You most certainly could open a ticket, since the problem is originally a .NET problem.
However I doubt you would get a fix before .NET 5 unless we implement the fix ourselves.

---------------

On a side note, this problem could be reproduced even on non bridged networks, simply disable IPv4 and IPv6 on any adapter and it would magically disappear from `GetAllNetworkInterfaces()`.
(We do this on same logging adapters to have the adapter only log external network without having the logging PC add any traffic)

![image](https://user-images.githubusercontent.com/1814900/71553891-26b17580-2a17-11ea-864c-bb676ff6c382.png)

**Comment by zbalkan** [comment] 2021-08-17 22:05
I'd like to add a workaround I've used for this: Getting a name from the description. The device interface description gives us something like this:
`Network adapter 'Adapter for loopback traffic capture' on local host`

Therefore, I use the string between the single quotes. However, since the names are still null, I use a new dictionary of generated device names as key with the interface as value.

**Closed** 2021-09-06 13:43 UTC
Labels: enhancement
