### ISSUE TITLE
Pcap.Version fails

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [chmorgan/sharppcap#20] opened 2017-03-13 13:01 UTC
NuGet package version 4.2.0
> pcap version can't be identified, you are either using an older version, or pcap is not installed.

**Comment by cmo-hms** [comment] 2017-03-18 23:01
Hi.

I'm not sure why that call wouldn't work. Is winpcap installed or npcap with winpcap compatibility? With a future version of sharppcap it will have npcap support built in.

Chris

**Comment by chmorgan** [comment] 2017-03-18 23:29
Sorry, wrong account before. Do you have winpcap or npcap with winpcap compatibility installed? If you are missing the libraries that method can fail.

**Comment by ImaginaryDevelopment** [comment] 2017-03-18 23:31
yeah, I didn't have it installed, had no idea what winpcap or npcap were. Eventually, I figured out what they were. Installed them, and then it worked.

**Comment by chmorgan** [comment] 2017-03-19 00:31
Ahh that makes sense. Its a little tough to know for sure what the issue is but I'm guessing that message could be clarified by saying that it is likely that pcap is not installed and possible, but less likely, that you are using an old version of pcap.

**Comment by chmorgan** [comment] 2017-05-06 19:09
Committed a clarification to the exception to lean towards pcap not being installed vs. the use of an old pcap version, which is far less likely.

**Closed by chmorgan** 2017-05-06 19:09 UTC
