### ISSUE TITLE
Recent memory management changes broke parsing large wireshark files

### ISSUE THREAD

**Issue by twa89** [chmorgan/sharppcap#177] opened 2020-12-23 20:10 UTC
I use SharpPcap to parse wireshark files.  When upgrading from 5.1 to 5.3 reading large files now always crashes with out of memory errors down in PacketDotNet.  The wireshark files are over 1.5 Gb in size.   I see in PacketDotNet a new memory component was added as a dependency.  This change is likely the cause of the crashes.  Version 5.1 parses 6 Gb files just fine.

**Comment by chmorgan** [comment] 2021-01-05 01:30
Hmm. I wonder what might have changed.

Are you holding onto any packets in your code? I'm not suggesting it isn't PacketDotNet but the changes I'm seeing back to early 2019 don't appear to affect memory as a whole.

Can you try out the older PacketDotNet version with the newer SharpPcap to confirm this is the issue?

**Comment by chmorgan** [comment] 2021-01-05 01:33
And I thought I saw this over on PacketDotNet. Which memory component? Maybe this is something broken external to both projects??

**Comment by twa89** [comment] 2021-01-05 14:04
Hi,

No, the application does not keep the packet in memory after decoding.

I can give that a try if they are compatible.

-Tom

**Comment by chmorgan** [comment] 2021-01-08 01:47
Yeah they should be compatible. The other option is for you to provide the large capture file that reproduces the issue so we can test here.

**Comment by chmorgan** [comment] 2021-01-08 01:55
@twa89 you can drop it on a file share somewhere if you'd like me to take a look at it.

**Comment by twa89** [comment] 2021-01-09 21:53
I emailed Chris a link to it on Egnite.  I tried to run 5.3 version with older version of PacketDotNet but it throws an exception saying it cannot find the right version of PacketDotNet

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'PacketDotNet, Version=1.1.1.0, Culture=neutral, PublicKeyToken=451414c7667b2a58' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at BACnetPacketEngine.PacketEngine.GetDeviceList()
   at BACnetPacketEngine.PacketEngine..ctor() in C:\dev\bacproTool\BACProService\PacketEngine\PacketEngine.cs:line 337
   at BACProService.Program.Main(String[] args) in C:\dev\bacproTool\BACProService\BACProService\Program.cs:line 68

**Comment by twa89** [comment] 2021-01-09 22:19
Here are the two out of memory exceptions.  My system has 16 GB of RAM and when running my process never gets above 500 MB.

1/9/2021 4:13:50 PM  System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at SharpPcap.LibPcap.PcapDevice.MarshalRawPacket(IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.PcapDevice.PacketHandler(IntPtr param, IntPtr header, IntPtr data)
   at SharpPcap.LibPcap.Windows.pcap_dispatch(IntPtr adaptHandle, Int32 count, pcap_handler callback, IntPtr ptr)
   at SharpPcap.LibPcap.PcapDevice.CaptureThread(CancellationToken cancellationToken)
   at SharpPcap.LibPcap.PcapDevice.Capture()
   at BACnetPacketEngine.PacketEngine.Connection..ctor(ICaptureDevice device, String dbName, String fileName) in C:\dev\bacproTool\BACProService\PacketEngine\Connection.cs:line 469
   at BACnetPacketEngine.PacketEngine.FileOpenThread() in C:\dev\bacproTool\BACProService\PacketEngine\PacketEngine.cs:line 1117
1/9/2021 4:13:50 PM  End parsing pcap file.
1/9/2021 4:13:50 PM  System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at PacketDotNet.Utils.ByteArraySegment.set_Length(Int32 value) in C:\dev\packetDotNet\packetnet\PacketDotNet\Utils\ByteArraySegment.cs:line 149
   at PacketDotNet.Utils.ByteArraySegment..ctor(ByteArraySegment byteArraySegment) in C:\dev\packetDotNet\packetnet\PacketDotNet\Utils\ByteArraySegment.cs:line 94
   at PacketDotNet.TcpPacket..ctor(ByteArraySegment byteArraySegment, Packet parentPacket) in C:\dev\packetDotNet\packetnet\PacketDotNet\TcpPacket.cs:line 120
   at PacketDotNet.IPPacket.ParseNextSegment(ByteArraySegment payload, ProtocolType protocolType, Packet parentPacket) in C:\dev\packetDotNet\packetnet\PacketDotNet\IPPacket.cs:line 280
   at PacketDotNet.IPv6Packet.<.ctor>b__5_0() in C:\dev\packetDotNet\packetnet\PacketDotNet\IPv6Packet.cs:line 148
   at PacketDotNet.LazySlim`1.CreateValue() in C:\dev\packetDotNet\packetnet\PacketDotNet\LazySlim.cs:line 64
   at PacketDotNet.LazySlim`1.get_Value() in C:\dev\packetDotNet\packetnet\PacketDotNet\LazySlim.cs:line 47
   at PacketDotNet.Packet.RecursivelyUpdateCalculatedValues() in C:\dev\packetDotNet\packetnet\PacketDotNet\Packet.cs:line 406
   at PacketDotNet.Packet.RecursivelyUpdateCalculatedValues() in C:\dev\packetDotNet\packetnet\PacketDotNet\Packet.cs:line 408
   at PacketDotNet.Packet.get_BytesSegment() in C:\dev\packetDotNet\packetnet\PacketDotNet\Packet.cs:line 75
   at PacketDotNet.Packet.get_Bytes() in C:\dev\packetDotNet\packetnet\PacketDotNet\Packet.cs:line 65
   at BACnetPacketEngine.PacketEngine.Connection.BackgroundThread() in C:\dev\bacproTool\BACProService\PacketEngine\Connection.cs:line 1334

**Comment by chmorgan** [comment] 2021-01-10 00:00
Thanks for sending the download info over.

How are you parsing the file with sharppcap? Is the command line packet
reading example equivalent to your use case? Does it run out of memory if
you run your capture file through it?

Chris

**Comment by twa89** [comment] 2021-01-10 01:16
The tool is a C# windows service.   I register the onPacketArrive callback, in the callback I call the parse function and write it to a new file.  Every minute I start a new file so that the entire file is sliced into 1 minute files.

**Comment by chmorgan** [comment] 2021-01-10 01:48
@twa89 does it occur if you run the ReadingCaptureFile example app? I'm trying to nail down how to reproduce the issue here.

**Comment by twa89** [comment] 2021-01-10 18:30
I tried the read example in 5.3 and it doesn't work with the big file, the link layer type comes in NULL.  I tried with a smaller file and it reads ok.  Wireshark opens the big capture file ok and so does SharpPcap 5.1.

This code is similar to what the tool does.  (program.cs from read example)


using System;
using SharpPcap;
using SharpPcap.LibPcap;
using PacketDotNet;
using System.IO;

namespace ReadingCaptureFile
{
    public class Program
    {
        public static void Main(string[] args)
        {
            string ver = SharpPcap.Version.VersionString;

            /* Print SharpPcap version */
            Console.WriteLine("SharpPcap {0}, ReadingCaptureFile", ver);
            Console.WriteLine();

            Console.WriteLine();

            // read the file from stdin or from the command line arguments
            string capFile;
            if (args.Length == 0)
            {
                Console.Write("-- Please enter an input capture file name: ");
                capFile = Console.ReadLine();
            }
            else
            {
                // use the first argument as the filename
                capFile = args[0];
            }

            Console.WriteLine("opening '{0}'", capFile);

            ICaptureDevice device;

            try
            {
                // Get an offline device
                device = new CaptureFileReaderDevice(capFile);

                // Open the device
                device.Open();
            }
            catch (Exception e)
            {
                Console.WriteLine("Caught exception when opening file" + e.ToString());
                return;
            }

            // Register our handler function to the 'packet arrival' event
            device.OnPacketArrival +=
                new PacketArrivalEventHandler(device_OnPacketArrival);

            Console.WriteLine();
            Console.WriteLine
                ("-- Capturing from '{0}', hit 'Ctrl-C' to exit...",
                capFile);

            // Start capture 'INFINTE' number of packets
            // This method will return when EOF reached.
            device.Capture();

            // Close the pcap device
            device.Close();
            Console.WriteLine("-- End of file reached.");
            Console.Write("Hit 'Enter' to exit...");
            Console.ReadLine();
        }

        private static int packetIndex = 0;

        public static CaptureFileWriterDevice FileWriter { get; private set; }

        /// <summary>
        /// Prints the source and dest MAC addresses of each received Ethernet frame
        /// </summary>
        private static void device_OnPacketArrival(object sender, CaptureEventArgs e)
        {
            string CaptureFile = "c:\\dev\\tempfile.pcap";

            if (FileWriter == null)
            {
   
                FileWriter = new CaptureFileWriterDevice((PacketDotNet.LinkLayers)e.Packet.LinkLayerType, 65536, CaptureFile, FileMode.Open);
            }

            if (e.Packet.LinkLayerType == LinkLayers.Ethernet)
            {
                var packet = PacketDotNet.Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);
                var ethernetPacket = (EthernetPacket)packet;

                FileWriter.Write(e.Packet);

                if (packetIndex % 10000 == 0)
                {
                    FileWriter.Close();
                    FileWriter = new CaptureFileWriterDevice((PacketDotNet.LinkLayers)e.Packet.LinkLayerType, 65536, CaptureFile, FileMode.Open);
                    Console.WriteLine("Processed {0} packets", packetIndex);
                }

                //Console.WriteLine("{0} At: {1}:{2}: MAC:{3} -> MAC:{4}",
                //                  packetIndex,
                //                  e.Packet.Timeval.Date.ToString(),
                //                  e.Packet.Timeval.Date.Millisecond,
                //                  ethernetPacket.SourceHardwareAddress,
                //                  ethernetPacket.DestinationHardwareAddress);
                packetIndex++;
            }
        }
    }
}

**Comment by chmorgan** [comment] 2021-01-12 13:32
@twa89 sent you an email, the download link expired since it took me until this morning to pull the file down. Can you resend?

**Comment by chmorgan** [comment] 2021-01-14 02:27
@twa89 sent you an email the other day with the results of testing. Any thoughts?

**Comment by twa89** [comment] 2021-01-14 04:23
I saw, I will look at it probably tomorrow night.

**Comment by chmorgan** [comment] 2021-02-23 02:35
Hi @twa89. I haven't been back on this but I also wasn't able to get VS to provide any kind of reasonable profiling output. Did the idea of adding a yield to the foreground code when the queue gets to a particular size help any to let the background thread run to process the queue? That would seem to avoid the issue you were seeing where memory grows due to the queue growing in size to millions of packets. Thoughts? Did you have any other progress resolving it?

**Comment by chmorgan** [comment] 2021-03-06 01:12
I'm glad to hear you were able to get it behaving better in terms of a lower memory footprint with a small pause. We did have a number of improvements to lazy packet parsing that could have improved the speed on the packetdotnet side but maybe its a real issue hidden somewhere that degraded performance. Happy to look into it further if you or anyone has any pointers on where to look.

**Closed by chmorgan** 2021-03-06 01:12 UTC
