### ISSUE TITLE
Example6.DumpTCP.cs   System.NotImplementedException:“Protocol of 3584 is not implemented”

### ISSUE THREAD

**Issue by chenli118** [chmorgan/sharppcap#68] opened 2019-05-28 06:00 UTC
I try  winPcap.Open(SharpPcap.WinPcap.OpenFlags.DataTransferUdp | SharpPcap.WinPcap.OpenFlags.NoCaptureLocal, readTimeoutMilliseconds);

in 
method "device_OnPacketArrival"
 line:    

  var tcpPacket = (PacketDotNet.TcpPacket)packet.Extract(typeof(PacketDotNet.TcpPacket));

**Comment by jehrich** [comment] 2019-05-28 15:23
I'm having this issue as well. The root cause appears to be that the link layer info is missing in the packet passed to the event handler (`CaptureEventArgs e`).

More specifically, the link layer argument being NULL in the line: `var packet = Packet.ParsePacket(e.Packet.LinkLayerType, e.Packet.Data);`

Changing this to `var packet = Packet.ParsePacket(LinkLayers.Ethernet, e.Packet.Data);` works around the issue for me, but is clearly not a good permanent solution.

Maybe someone knows why the LinkLayer info might not be populated in the `CaptureEventArgs`...?

**Comment by chmorgan** [comment] 2019-05-29 23:24
@chenli118, @jehrich are you using Npcap? What adapters are you capturing on? I checked the code flow and the LinkType (linkType internally) is set in PcapDevice.cs when Active is set which occurs when a capture file is opened or a live capture is opened. This code hasn't changed in a while so its unclear why this wouldn't be working unless you are capturing on a device that doesn't provide a link layer, I think a raw capture device might do that.

**Comment by jehrich** [comment] 2019-05-30 01:59
I'm using Npcap (v0.995) and the adapter is listed as `Intel(R) 82574L Gigabit Network Connection` but it's actually a virtualized adapter running in VMware Workstation.

**Comment by chmorgan** [comment] 2019-05-30 15:55
@jehrich if you could find that location I mentioned in PcapDevice.cs and print out the output there when you open the adapter that could be helpful in confirming the value of the linktype. It would require building sharppcap from source but afaik this is the first the issue has been seen, not sure if its a widespread one or limited.

**Comment by chmorgan** [comment] 2019-08-07 00:02
Closing as the original poster hasn't responded for a while.

**Closed by chmorgan** 2019-08-07 00:02 UTC
